### ISSUE TITLE
version pinpointing causes conflicts for applications that depend on pysatochip

### ISSUE THREAD

**Issue by PiRK** [Toporin/pysatochip#2]
I noticed that pysatochip 0.12.3 is pinpointing specific versions of libraries in https://github.com/Toporin/pysatochip/blob/master/requirements.txt

This is causing me some headaches when Electrum ABC already has dependencies to  different/newer versions of those libraries. Do you think it would be possible to replace all `==` by `>=` in the requirements, to be more future proof and cause less conflicts?

For now I'm able to work around the issue, so it is not urgent. But something to think about for future releases.
It only causes problems when I try to build a deterministic release, with all version numbers pinpointed on the Electrum ABC side as well. Then there are conflicts that I need to solve by downgrading some library versions on my end.

**Comment by Toporin** [comment]
Fixed in Pysatochip v0.12.3 and higher, see commit https://github.com/Toporin/pysatochip/commit/616864c06c5c7348e1367bde00b52c4a50d116b6
