### ISSUE TITLE
card_type not defined when first opening a wallet in Electrum ABC

### ISSUE THREAD

**Issue by PiRK** [Toporin/pysatochip#3]
When I first open my satochip wallet, I get the message "Enter the pin for your None"

![Screenshot from 2021-12-14 08-54-53](https://user-images.githubusercontent.com/419570/145957895-1f3edab9-f605-46a4-923a-1c9635db123e.png)

If I open the wallet again later in the same session, it correctly says "Enter the pin for your Satochip"

This is a very minor issue, I'm submitting it just in case you have an idea for a very simple fix. Maybe there is anything that can be done on the Electrum side to cause `card_type` to be defined earlier in the wallet opening process?

Or else, maybe just add a fallback in `pysatochip.CardConnector`:
    
    def card_verify_PIN(self):
        logger.debug("In card_verify_PIN")
        
        while (self.card_present):
            if self.pin is None:
                is_PIN= False
                if self.client is not None:
    +               card_type = self.card_type or "card"
    +               msg = f'Enter the PIN for your {card_type}:'
    -               msg = f'Enter the PIN for your {self.card_type}:'
                    (is_PIN, pin_0)= self.client.PIN_dialog(msg) #todo: use request?

**Comment by Toporin** [comment]
Thanks for bringing this! It will be fixed in the next release!
